spring:
  application:
    name: todomanager
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todomanager_db}
    name: ${DB_NAME:todomanager_db}
    username: ${DB_USER:nameless}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: 1234

#logging:
#  level:
#    root: debug